version: "3.7"
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "test_password"
      MYSQL_DATABASE: "test_database"
    restart: always
    ports:
      - "3306:3306"
